#!/usr/bin/env python3
"""Replay test_g1_to_bumi3's BUMI3 qpos output in MuJoCo."""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import mujoco
import mujoco.viewer
import numpy as np


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--replay", required=True,
                        help="*_replay.json generated by test_g1_to_bumi3")
    parser.add_argument("--loop", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(Path(args.replay).read_text())
    model = mujoco.MjModel.from_xml_path(manifest["xml"])
    data = mujoco.MjData(model)
    qpos = np.load(manifest["qpos"], allow_pickle=False)
    if qpos.ndim != 2 or qpos.shape[1] != model.nq:
        raise ValueError(f"qpos shape {qpos.shape} does not match nq={model.nq}")
    fps = float(manifest["fps"])
    with mujoco.viewer.launch_passive(model, data) as viewer:
        while viewer.is_running():
            start = time.monotonic()
            for index, frame in enumerate(qpos):
                if not viewer.is_running():
                    return
                data.qpos[:] = frame
                mujoco.mj_forward(model, data)
                viewer.sync()
                remaining = start + (index + 1) / fps - time.monotonic()
                if remaining > 0.0:
                    time.sleep(remaining)
            if not args.loop:
                return


if __name__ == "__main__":
    main()
